services:
  # Backend API
  - type: web
    name: hyperliquid-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: FLASK_ENV
        value: production
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: hyperliquid-db
          property: connectionString
      - key: HYPERLIQUID_ENV
        value: mainnet
      - key: HYPERLIQUID_API_URL
        value: https://api.hyperliquid.xyz

  # Frontend
  - type: web
    name: hyperliquid-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://hyperliquid-backend.onrender.com/api

databases:
  - name: hyperliquid-db
    databaseName: hyperliquid_tracker
    user: hyperliquid_user