databases:
  - name: hyperliquid-db
    databaseName: hyperliquid_tracker
    user: hyperliquid_user
    plan: free

services:

  # Backend API
  - type: web
    name: hyperliquid-api
    env: python
    plan: free
    runtime: python-3.13.4
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: API_HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        fromDatabase:
          name: hyperliquid-db
          property: connectionString

  # Frontend (disabled for now - deploy backend first)
  # - type: web
  #   name: hyperliquid-frontend
  #   env: static
  #   buildCommand: cd frontend && npm install && npm run build
  #   staticPublishPath: frontend/dist