services:
  # Backend API
  - type: web
    name: hyperliquid-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False

  # Frontend
  - type: web
    name: hyperliquid-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://hyperliquid-api-4uis.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html